use anyhow::Result;
use chrono::Datelike;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::HashMap;

use super::parameters::Parameters;

/// 基础参数结构 - 包含所有生成器共用的参数
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaseParams {
    // 项目基础信息
    pub project_name: String,
    pub project_version: String,
    pub project_description: Option<String>,
    pub author: Option<String>,
    pub license: String,

    // Git相关
    pub enable_git: bool,
    pub enable_precommit: bool,

    // 服务器配置（适用于Web框架）
    pub host: Option<String>,
    pub port: Option<u16>,

    // 通用功能开关
    pub enable_swagger: bool,
    pub enable_cors: bool,
    pub enable_logging: bool,
    pub enable_recovery: bool,
    pub enable_rate_limit: bool,
    pub enable_jwt: bool,
    pub enable_database: bool,
    pub enable_redis: bool,
    pub enable_grpc: bool,
    pub enable_middleware: bool,

    // 网络配置
    pub default_host: Option<String>,
    pub default_port: Option<u16>,

    // 数据库配置
    pub database_type: Option<String>,

    // 语言特定配置
    pub language_version: Option<String>,
    pub module_name: Option<String>,
    pub enable_modules: bool,
    pub enable_cgo: bool,
    pub build_tags: Vec<String>,
    pub enable_vendor: bool,
}

impl Default for BaseParams {
    fn default() -> Self {
        Self {
            // 项目基础信息
            project_name: String::new(),
            project_version: "0.1.0".to_string(),
            project_description: None,
            author: None,
            license: "MIT".to_string(),

            // Git相关
            enable_git: true,
            enable_precommit: false,

            // 服务器配置
            host: Some("127.0.0.1".to_string()),
            port: Some(8080),

            // 通用功能开关
            enable_swagger: true,
            enable_cors: true,
            enable_logging: true,
            enable_recovery: true,
            enable_rate_limit: false,
            enable_jwt: false,
            enable_database: false,
            enable_redis: false,
            enable_grpc: false,
            enable_middleware: true,

            // 网络配置
            default_host: None,
            default_port: None,

            // 数据库配置
            database_type: None,

            // 语言特定配置
            language_version: Some("1.21".to_string()), // Go默认版本
            module_name: None,
            enable_modules: true,
            enable_cgo: false,
            build_tags: Vec::new(),
            enable_vendor: false,
        }
    }
}

impl Parameters for BaseParams {
    fn validate(&self) -> Result<()> {
        use super::validation;

        validation::validate_project_name(&self.project_name)?;

        if self.license.is_empty() {
            return Err(anyhow::anyhow!("License cannot be empty"));
        }

        if let Some(ref host) = self.host {
            validation::validate_host(host)?;
        }

        if let Some(port) = self.port {
            validation::validate_port(port)?;
        }

        if self.enable_database && self.database_type.is_none() {
            return Err(anyhow::anyhow!(
                "Database type must be specified when database is enabled"
            ));
        }

        Ok(())
    }

    fn to_template_context(&self) -> HashMap<String, Value> {
        let mut context = HashMap::new();

        // 项目基础信息
        context.insert("project_name".to_string(), json!(self.project_name));
        context.insert("project_version".to_string(), json!(self.project_version));
        context.insert("license".to_string(), json!(self.license));

        // 项目名称的不同格式
        context.insert(
            "project_name_pascal".to_string(),
            json!(crate::constants::string_utils::to_pascal_case(
                &self.project_name
            )),
        );
        context.insert(
            "project_name_snake".to_string(),
            json!(crate::constants::string_utils::to_snake_case(
                &self.project_name
            )),
        );

        // 为了兼容性添加别名
        context.insert("ProjectName".to_string(), json!(self.project_name));
        context.insert("cargo_version".to_string(), json!(self.project_version));

        // 项目描述
        if let Some(ref description) = self.project_description {
            context.insert("project_description".to_string(), json!(description));
            context.insert("cargo_description".to_string(), json!(description));
        } else {
            let default_description =
                format!("A {} project generated by Scaffold-Gen", self.project_name);
            context.insert(
                "project_description".to_string(),
                json!(default_description),
            );
            context.insert("cargo_description".to_string(), json!(default_description));
        }

        // 作者信息
        if let Some(ref author) = self.author {
            context.insert("author".to_string(), json!(author));
        }

        // 当前年份
        let current_year = chrono::Utc::now().year();
        context.insert("year".to_string(), json!(current_year));

        // Git相关
        context.insert("enable_git".to_string(), json!(self.enable_git));
        context.insert("enable_precommit".to_string(), json!(self.enable_precommit));

        // 服务器配置
        if let Some(ref host) = self.host {
            context.insert("host".to_string(), json!(host));
            context.insert("default_host".to_string(), json!(host));
        }
        if let Some(port) = self.port {
            context.insert("port".to_string(), json!(port));
            context.insert("default_port".to_string(), json!(port));
        }

        // 通用功能开关
        context.insert("enable_swagger".to_string(), json!(self.enable_swagger));
        context.insert("enable_cors".to_string(), json!(self.enable_cors));
        context.insert("enable_logging".to_string(), json!(self.enable_logging));
        context.insert("enable_recovery".to_string(), json!(self.enable_recovery));
        context.insert(
            "enable_rate_limit".to_string(),
            json!(self.enable_rate_limit),
        );
        context.insert("enable_jwt".to_string(), json!(self.enable_jwt));
        context.insert("enable_database".to_string(), json!(self.enable_database));
        context.insert("enable_redis".to_string(), json!(self.enable_redis));

        // 数据库配置
        if let Some(ref db_type) = self.database_type {
            context.insert("database_type".to_string(), json!(db_type));
        }

        // 语言特定配置
        if let Some(ref version) = self.language_version {
            context.insert("go_version".to_string(), json!(version));
            context.insert("language_version".to_string(), json!(version));
        }
        if let Some(ref module) = self.module_name {
            context.insert("module_name".to_string(), json!(module));
        }
        context.insert("enable_modules".to_string(), json!(self.enable_modules));
        context.insert("enable_cgo".to_string(), json!(self.enable_cgo));
        context.insert("build_tags".to_string(), json!(self.build_tags));
        context.insert("enable_vendor".to_string(), json!(self.enable_vendor));

        context
    }
}

impl BaseParams {
    /// 创建新的基础参数
    pub fn new(project_name: String) -> Self {
        Self {
            project_name: project_name.clone(),
            module_name: Some(project_name),
            ..Default::default()
        }
    }

    /// 设置项目描述
    pub fn with_description(mut self, description: String) -> Self {
        self.project_description = Some(description);
        self
    }

    /// 设置作者
    pub fn with_author(mut self, author: String) -> Self {
        self.author = Some(author);
        self
    }

    /// 设置许可证
    pub fn with_license(mut self, license: String) -> Self {
        self.license = license;
        self
    }

    /// 设置服务器配置
    #[allow(dead_code)]
    pub fn with_server(mut self, host: String, port: u16) -> Self {
        self.host = Some(host);
        self.port = Some(port);
        self
    }

    /// 设置数据库配置
    #[allow(dead_code)]
    pub fn with_database(mut self, db_type: String) -> Self {
        self.enable_database = true;
        self.database_type = Some(db_type);
        self
    }

    /// 设置语言版本
    #[allow(dead_code)]
    pub fn with_language_version(mut self, version: String) -> Self {
        self.language_version = Some(version);
        self
    }

    /// 启用功能
    #[allow(dead_code)]
    pub fn enable_feature(mut self, feature: &str) -> Self {
        match feature {
            "swagger" => self.enable_swagger = true,
            "cors" => self.enable_cors = true,
            "logging" => self.enable_logging = true,
            "recovery" => self.enable_recovery = true,
            "rate_limit" => self.enable_rate_limit = true,
            "jwt" => self.enable_jwt = true,
            "database" => self.enable_database = true,
            "redis" => self.enable_redis = true,
            "git" => self.enable_git = true,
            "precommit" => self.enable_precommit = true,
            "modules" => self.enable_modules = true,
            "cgo" => self.enable_cgo = true,
            "vendor" => self.enable_vendor = true,
            _ => {} // 忽略未知功能
        }
        self
    }

    /// 禁用功能
    #[allow(dead_code)]
    pub fn disable_feature(mut self, feature: &str) -> Self {
        match feature {
            "swagger" => self.enable_swagger = false,
            "cors" => self.enable_cors = false,
            "logging" => self.enable_logging = false,
            "recovery" => self.enable_recovery = false,
            "rate_limit" => self.enable_rate_limit = false,
            "jwt" => self.enable_jwt = false,
            "database" => self.enable_database = false,
            "redis" => self.enable_redis = false,
            "git" => self.enable_git = false,
            "precommit" => self.enable_precommit = false,
            "modules" => self.enable_modules = false,
            "cgo" => self.enable_cgo = false,
            "vendor" => self.enable_vendor = false,
            _ => {} // 忽略未知功能
        }
        self
    }
}

/// 参数继承trait - 用于扩展基础参数
pub trait InheritableParams: Parameters {
    /// 获取基础参数的引用
    fn base_params(&self) -> &BaseParams;

    /// 获取基础参数的可变引用
    #[allow(dead_code)]
    fn base_params_mut(&mut self) -> &mut BaseParams;

    /// 从基础参数创建
    #[allow(dead_code)]
    fn from_base(base: BaseParams) -> Self;

    /// 获取扩展的模板上下文（子类特有的参数）
    fn extended_template_context(&self) -> HashMap<String, Value> {
        HashMap::new()
    }
}

/// 为实现了InheritableParams的类型提供默认的Parameters实现
impl<T: InheritableParams> Parameters for T {
    fn validate(&self) -> Result<()> {
        // 首先验证基础参数
        self.base_params().validate()?;

        // 子类可以重写此方法添加额外验证
        Ok(())
    }

    fn to_template_context(&self) -> HashMap<String, Value> {
        let mut context = self.base_params().to_template_context();

        // 合并扩展的模板上下文
        let extended_context = self.extended_template_context();
        context.extend(extended_context);

        context
    }
}
