//! `BaseParams` 的模板上下文构建 —— 从 `base_parameters.rs` 拆出的 `to_template_context` 实体。
//!
//! 这里只负责把 `BaseParams` 的字段（含历史别名 `cargo_version`/`ProjectName`/
//! `default_host`/`default_port`/`go_version`）展开为模板渲染用的键值上下文。

use chrono::Datelike;
use serde_json::{Value, json};
use std::collections::HashMap;

use super::base_parameters::BaseParams;

/// 把 `BaseParams` 展开为模板上下文（键集与别名行为保持与历史逐字一致）。
pub fn build_base_context(params: &BaseParams) -> HashMap<String, Value> {
    let mut context = HashMap::new();

    // 项目基础信息
    context.insert("project_name".to_string(), json!(params.project_name));
    context.insert("project_version".to_string(), json!(params.project_version));
    context.insert("license".to_string(), json!(params.license));

    // 项目名称的不同格式
    context.insert(
        "project_name_pascal".to_string(),
        json!(crate::constants::string_utils::to_pascal_case(
            &params.project_name
        )),
    );
    context.insert(
        "project_name_snake".to_string(),
        json!(crate::constants::string_utils::to_snake_case(
            &params.project_name
        )),
    );
    context.insert(
        "proto_package".to_string(),
        json!(crate::constants::string_utils::to_proto_ident(
            &params.project_name
        )),
    );

    // 为了兼容性添加别名
    context.insert("ProjectName".to_string(), json!(params.project_name));
    context.insert("cargo_version".to_string(), json!(params.project_version));

    // 项目描述
    if let Some(ref description) = params.project_description {
        context.insert("project_description".to_string(), json!(description));
        context.insert("cargo_description".to_string(), json!(description));
    } else {
        let default_description = format!(
            "A {} project generated by Scaffold-Gen",
            params.project_name
        );
        context.insert(
            "project_description".to_string(),
            json!(default_description),
        );
        context.insert("cargo_description".to_string(), json!(default_description));
    }

    // 作者信息
    if let Some(ref author) = params.author {
        context.insert("author".to_string(), json!(author));
    }

    // 当前年份
    let current_year = chrono::Utc::now().year();
    context.insert("year".to_string(), json!(current_year));

    // Git相关
    context.insert("enable_git".to_string(), json!(params.enable_git));
    context.insert(
        "enable_precommit".to_string(),
        json!(params.enable_precommit),
    );

    // 服务器配置
    if let Some(ref host) = params.host {
        context.insert("host".to_string(), json!(host));
        context.insert("default_host".to_string(), json!(host));
    }
    if let Some(port) = params.port {
        context.insert("port".to_string(), json!(port));
        context.insert("default_port".to_string(), json!(port));
    }

    // 通用功能开关
    context.insert("enable_swagger".to_string(), json!(params.enable_swagger));
    context.insert("enable_cors".to_string(), json!(params.enable_cors));
    context.insert("enable_logging".to_string(), json!(params.enable_logging));
    context.insert("enable_recovery".to_string(), json!(params.enable_recovery));
    context.insert(
        "enable_rate_limit".to_string(),
        json!(params.enable_rate_limit),
    );
    context.insert("enable_jwt".to_string(), json!(params.enable_jwt));
    context.insert("enable_database".to_string(), json!(params.enable_database));
    context.insert("enable_redis".to_string(), json!(params.enable_redis));

    // 数据库配置
    if let Some(ref db_type) = params.database_type {
        context.insert("database_type".to_string(), json!(db_type));
    }

    // 语言特定配置
    if let Some(ref version) = params.language_version {
        context.insert("go_version".to_string(), json!(version));
        context.insert("language_version".to_string(), json!(version));
    }
    if let Some(ref module) = params.module_name {
        context.insert("module_name".to_string(), json!(module));
    }
    context.insert("enable_modules".to_string(), json!(params.enable_modules));
    context.insert("enable_cgo".to_string(), json!(params.enable_cgo));
    context.insert("build_tags".to_string(), json!(params.build_tags));
    context.insert("enable_vendor".to_string(), json!(params.enable_vendor));

    context
}

#[cfg(test)]
#[path = "context_tests.rs"]
mod tests;
