FROM golang:{{go_version}}-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api api/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/
COPY --from=builder /app/api .
COPY --from=builder /app/etc ./etc
EXPOSE {{Port}}
CMD ["./api", "-f", "etc/api.yaml"]
